Just a bunch of stuff • Fixed more authorization • changed routes • MOAR BOOTSTRAP!!! • Procfile • cleanup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,56 +1,68 @@
-#!/bin/sh
+#!/usr/bin/env sh
 
+# Set up Rails app. Run this script immediately after cloning the codebase.
+# https://github.com/thoughtbot/guides/tree/master/protocol
+
+# Exit if any subcommand fails
 set -e
 
 # Set up Ruby dependencies via Bundler
 gem install bundler --conservative
 bundle check || bundle install
 
-# # Set up configurable environment variables
-# if [ ! -f .env ]; then
-#   cp .sample.env .env
-# fi
-
-# Generate a new secret
-echo "Here's a secret. Use it in config/secrets.yml for your development and testing configs."
-rake secret
-echo "And here's one for config/initializers/secret_token.rb"
-rake secret
+# Set up configurable environment variables
+if [ ! -f .env ]; then
+  cp .sample.env .env
+fi
 
 # Set up database and add any development seed data
 bundle exec rake db:setup dev:prime
+
+# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
+mkdir -p .git/safe
 
 # Pick a port for Foreman
 if ! grep --quiet --no-messages --fixed-strings 'port' .foreman; then
   printf 'port: 3000\n' >> .foreman
 fi
 
+# Mailcatcher needed for local email testing
+if ! command -v mailcatcher > /dev/null; then
+  gem install mailcatcher
+  mailcatcher
+fi
+
+# Redis needed for Resque
+if ! command redis-server ping > /dev/null; then
+  brew install redis
+fi
+
+
 if ! command -v foreman > /dev/null; then
   printf 'Foreman is not installed.\n'
   printf 'See https://github.com/ddollar/foreman for install instructions.\n'
 fi
 
-if ! command -v heroku >/dev/null; then
-  echo "The \`heroku' command is required to run this setup." >&2
-  echo "https://toolbelt.heroku.com/" >&2
-  exit 1
+# Only if this isn't CI
+# if [ -z "$CI" ]; then
+# fi
+
+# Set up the staging and production apps.
+if heroku join --app nestegg-staging &> /dev/null; then
+  git remote add staging git@heroku.com:nestegg-staging.git || true
+  printf 'You are a collaborator on the "nestegg-staging" Heroku app
+'
+else
+  printf 'Ask for access to the "nestegg-staging" Heroku app
+'
 fi
 
-# # Set up the staging and production apps.
-# if heroku join --app staffr-staging &> /dev/null; then
-#   git remote add staging git@heroku.com:staffr-staging.git || true
-#   printf 'You are a collaborator on the "staffr-staging" Heroku app
-# '
-# else
-#   printf 'Ask for access to the "staffr-staging" Heroku app
-# '
-# fi
+if heroku join --app nestegg-production &> /dev/null; then
+  git remote add production git@heroku.com:nestegg-production.git || true
+  printf 'You are a collaborator on the "nestegg-production" Heroku app
+'
+else
+  printf 'Ask for access to the "nestegg-production" Heroku app
+'
+fi
 
-# if heroku join --app staffr-production &> /dev/null; then
-#   git remote add production git@heroku.com:staffr-production.git || true
-#   printf 'You are a collaborator on the "staffr-production" Heroku app
-# '
-# else
-#   printf 'Ask for access to the "staffr-production" Heroku app
-# '
-# fi
